title: Chelsea Ramos # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a data scientist in the SF Bay Area with an electrical/product engineering background and 2+ years of experience in programming and data analysis. 
  <br>
  With a passion for machine learning, I am eager to gain and use data-driven insights, present deliverables, and collaborate effectively either in-person or remotely.
  <br>
  My projects include a minimum viable product for Airbnb review sentiment classification which you can try out at this link: tinyurl.com/rating-predictor (one of my Featured Projects).
  <br>
  When I'm not learning about or working on something programming or data science-related, I enjoy yoga, bike riding, and enjoying the sun. Fun Fact: I am originally from Honolulu, Hawai'i!
  Looking forward to connecting with you!
  <br><br>
  I am continuously learning and adding new projects, stay tuned! :)
  <br>
  Thank you for visiting.
  <br><br>
  <a href="https://www.linkedin.com/in/chelseanbr/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-164814770-1 # your Google Analytics tracking ID here
