title: Chelsea Ramos # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome! I am a data scientist in the SF Bay Area with a product/electrical engineering background and 2+ years of experience in programming and data analysis. 
  <br>
  My portfolio includes both individual and group projects and I am continuously learning and trying new things!
  <br>
  Thank you for visiting. Looking forward to connecting with you!
  <br>
  <a href="https://www.linkedin.com/in/chelseanbr/">View My LinkedIn Profile</a>
theme: jekyll-theme-minimal
google_analytics: UA-164814770-1 # your Google Analytics tracking ID here